NAMA :NABILA FARAPASYET
UNIVERSITAS :TELKOM UNIVERSITAS

--MST_CFI
CREATE TABLE MST_CIF  (
		  "CIFID" VARCHAR(10) PRIMARY KEY NOT NULL ,
		  "AOID" VARCHAR(10) NOT NULL ,
		  "DTJOIN" DATE NOT NULL , -- tanggal pembukaan
		  "FULLNM" VARCHAR(60) NOT NULL ,
		  "NPWP" VARCHAR(20) ,
		  "CIFTYPE" SMALLINT NOT NULL , -- jenis cif 0 - perorangan , 1 - non perorangan
		  "COUNTRYID" CHAR(2) NOT NULL ,
		  "FLGRELATED" SMALLINT NOT NULL , --TERKAIT BANK ATAU TIDAK
		  "STATUS" CHAR(1) ,
		  "FLGAPPRV" SMALLINT ,
		  "USRCRT" VARCHAR(5) NOT NULL ,
		  "DTCRT" TIMESTAMP NOT NULL ,SELECT CIFID, AOID, DTJOIN, STATUS FROM MST_CIF WHERE CIFID=0001277352 AND CIFID=0001277638
		  "USRUPD" VARCHAR(5) ,
		  "DTUPD" TIMESTAMP ,
		  "USRAPV" VARCHAR(5) ,
		  "DTAPPRV" TIMESTAMP)


--MST_CIFPERSNL
CREATE TABLE MST_CIFPERSNL (
		  "CIFID" VARCHAR(10) NOT NULL , 
		  "AOID" VARCHAR(10) NOT NULL , 
		  "FULLNM" VARCHAR(80) NOT NULL , 
		  "PREDEGREE" VARCHAR(16) , 
		  "POSTDEGREE" VARCHAR(16) , 
		  "SURENM" VARCHAR(50) NOT NULL , 
		  "MOTHRNM" VARCHAR(50) NOT NULL , 
		  "RELIGIONID" CHAR(1) NOT NULL , 
		  "MARRIAGEID" CHAR(1) NOT NULL , 
		  "LASTEDUID" VARCHAR(4) NOT NULL , 
		  "NPWP" VARCHAR(20) , 
		  "BRTDT" DATE NOT NULL , 
		  "BRTPLACE" VARCHAR(32) NOT NULL , 
		  "TYPEID" CHAR(2) NOT NULL , 
		  "IDNBR" VARCHAR(32) NOT NULL , 
		  "ADDR" VARCHAR(64) NOT NULL , 
		  "RT" VARCHAR(3) , 
		  "RW" VARCHAR(3) , 
		  "KELNM" VARCHAR(32) , 
		  "POSTALCODE" VARCHAR(5) NOT NULL , 
		  "KECNM" VARCHAR(32) , 
		  "CITYID" VARCHAR(4) NOT NULL , 
		  "PROVID" VARCHAR(2) NOT NULL , 
		  "COUNTRYID" VARCHAR(2) NOT NULL , 
		  "NOTELP" VARCHAR(16) , 
		  "NOFAX" VARCHAR(16) , 
		  "EXPDT" DATE NOT NULL , --masa berlaku jenis identitas
		  "STSNATION" SMALLINT NOT NULL  , 
		  "SEX" SMALLINT NOT NULL , 
		  "NOHP" VARCHAR(16) , 
		  "BLOODTYPE" VARCHAR(2) , 
		  "HOBBY" VARCHAR(20) , 
		  "INSURED" SMALLINT NOT NULL , 
		  "HOMEID" CHAR(1) NOT NULL , 
		  "OWNID" VARCHAR(4) NOT NULL , 
		  "ALIAS" VARCHAR(80) , 
		  "FLGCITIZEN" SMALLINT NOT NULL  , 
		  "NOTE" VARCHAR(150) , 
		  "NIP" VARCHAR(20) , 
		  "JOBID" VARCHAR(3) )   
		 
--A
SELECT *FROM MST_CIF A 
JOIN MST_CIFPERSNL B ON A.CIFID=B.CIFID
JOIN MST_CIFCOM C ON B.CIFID =C.CIFID
WHERE A.status=2

--B
SELECT CIFID,DTJOIN FROM MST_CFI WHERE TO_CHAR (DTJOIN, ‘MONTHS’) = ‘08’ AND TO_CHAR (DTJOIN, YEAR)=’2016’

--C
JUMLAH CIFID DIMANA AOID NILAI CIFID DITABEL MST_CIF SAMA DENGAN CIFID DI TABEL MST_CIFPRNSL SAMA

--D
SELECT CIFID, AOID, DTJOIN, STATUS FROM MST_CIF WHERE CIFID IN ('0001277352','0001277638');