CREATE TABLE "DBO     "."MST_CIF"  (
		  "CIFID" VARCHAR(10) NOT NULL , 
		  "AOID" VARCHAR(10) NOT NULL , 
		  "DTJOIN" DATE NOT NULL , -- tanggal pembukaan
		  "FULLNM" VARCHAR(60) NOT NULL , 
		  "NPWP" VARCHAR(20) , 
		  "CIFTYPE" SMALLINT NOT NULL , -- jenis cif 0 - perorangan , 1 - non perorangan
		  "COUNTRYID" CHAR(2) NOT NULL , 
		  "FLGRELATED" SMALLINT NOT NULL WITH DEFAULT 2 , --TERKAIT BANK ATAU TIDAK
		  "STATUS" CHAR(1) WITH DEFAULT '0' , 
		  "FLGAPPRV" SMALLINT WITH DEFAULT 0 , 
		  "USRCRT" VARCHAR(5) NOT NULL , 
		  "DTCRT" TIMESTAMP NOT NULL , 
		  "USRUPD" VARCHAR(5) , 
		  "DTUPD" TIMESTAMP , 
		  "USRAPV" VARCHAR(5) , 
		  "DTAPPRV" TIMESTAMP  )   
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW  ;

CREATE UNIQUE INDEX "DBO     "."IDX_MST_CIF" ON "DBO     "."MST_CIF" 
		("CIFID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;
ALTER TABLE "DBO     "."MST_CIF" 
	ADD CONSTRAINT "PK_MST_CIF" PRIMARY KEY
		("CIFID") ;

GRANT CONTROL ON TABLE "DBO     "."MST_CIF" TO USER "DB2PA724"  ;
