CREATE TABLE "DBO     "."MST_CIFPERSNL"  (
		  "CIFID" VARCHAR(10) NOT NULL , 
		  "AOID" VARCHAR(10) NOT NULL , 
		  "FULLNM" VARCHAR(80) NOT NULL , 
		  "PREDEGREE" VARCHAR(16) , 
		  "POSTDEGREE" VARCHAR(16) , 
		  "SURENM" VARCHAR(50) NOT NULL , 
		  "MOTHRNM" VARCHAR(50) NOT NULL , 
		  "RELIGIONID" CHAR(1) NOT NULL , 
		  "MARRIAGEID" CHAR(1) NOT NULL , 
		  "LASTEDUID" VARCHAR(4) NOT NULL , 
		  "NPWP" VARCHAR(20) , 
		  "BRTDT" DATE NOT NULL , 
		  "BRTPLACE" VARCHAR(32) NOT NULL , 
		  "TYPEID" CHAR(2) NOT NULL , 
		  "IDNBR" VARCHAR(32) NOT NULL , 
		  "ADDR" VARCHAR(64) NOT NULL , 
		  "RT" VARCHAR(3) , 
		  "RW" VARCHAR(3) , 
		  "KELNM" VARCHAR(32) , 
		  "POSTALCODE" VARCHAR(5) NOT NULL , 
		  "KECNM" VARCHAR(32) , 
		  "CITYID" VARCHAR(4) NOT NULL , 
		  "PROVID" VARCHAR(2) NOT NULL , 
		  "COUNTRYID" VARCHAR(2) NOT NULL , 
		  "NOTELP" VARCHAR(16) , 
		  "NOFAX" VARCHAR(16) , 
		  "EXPDT" DATE NOT NULL , --masa berlaku jenis identitas
		  "STSNATION" SMALLINT NOT NULL WITH DEFAULT 1 ,
		  "SEX" SMALLINT NOT NULL WITH DEFAULT 1 ,
		  "NOHP" VARCHAR(16) ,
		  "BLOODTYPE" VARCHAR(2) ,
		  "HOBBY" VARCHAR(20) ,
		  "INSURED" SMALLINT NOT NULL WITH DEFAULT 0 ,
		  "HOMEID" CHAR(1) NOT NULL ,
		  "OWNID" VARCHAR(4) NOT NULL ,
		  "ALIAS" VARCHAR(80) ,
		  "FLGCITIZEN" SMALLINT NOT NULL WITH DEFAULT 1 ,
		  "NOTE" VARCHAR(150) ,
		  "NIP" VARCHAR(20) ,
		  "JOBID" VARCHAR(3) )
		 IN "USERSPACE1"
		 ORGANIZE BY ROW  ;

CREATE UNIQUE INDEX "DBO     "."IDX_MST_CIFPERSNL" ON "DBO     "."MST_CIFPERSNL"
		("CIFID" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;
ALTER TABLE "DBO     "."MST_CIFPERSNL"
	ADD CONSTRAINT "PK_MST_CIFPERSNL" PRIMARY KEY
		("CIFID") ;

GRANT CONTROL ON TABLE "DBO     "."MST_CIFPERSNL" TO USER "DB2PA724"  ;
